### ISSUE TITLE
ftp issue

### ISSUE THREAD

**Issue by ghost** [addiks/gedit-gitmenu#2]
Hi!
When activate the plugin it becomes unavailable to work with documents opened by ftp with the Nautilus helper. The connection becomes very slow and Find feature just doesn't work any more. Disabling the plugin helps.

**Comment by addiks** [comment]
Wow, you are right. I lived with that for a long time now thinking that was just how gedit performed over network. Never thought that this might be one of my plugins misbehaving. Amazing what a second pair of eyes can do for you. Thank you big times for the notice.

I will look into this right now. I cannot guarantee a fast fix though as networking issues can sometimes be hard to debug and i don't have too much time to throw at these project's.

**Comment by addiks** [comment]
I have just pushed a new version with a fix that might help. Can you please test it and report back?

**Comment by ghost** [comment]
@addiks It doesn't change - the Find dialog still stale when the plugin activated...

**Comment by addiks** [comment]
Looks like there were even more issues than i thought. I have now moved the update-state process into it's own thread. That should stop blocking the open-file dialog, which i assume is what you mean by "find dialog". Before that i thought you meant the Ctrl+F dialog for searching a text inside a file. The other patch above was an added 15 second cache for search-the-git-repository process which was executed 4-6 times per keystroke. Please try this new version and report back if this finally fixes your problem. If not, please describe in detail every step you do to reproduce the problem.

**Comment by ghost** [comment]
@addiks Thanks, I actually meant Ctrl-F feature, not Open file one. Also it would be great if you have some versioning for releases like 'build xxx' in 'About' section of the plugin to ensure that I'm using the correct version...

**Comment by ghost** [comment]
@addiks Everything works fine with the new version now! Thanks! :)
